/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Servers */
        get: operations["list_my_servers_servers_get"];
        put?: never;
        /** Create Server */
        post: operations["create_server_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public Servers */
        get: operations["list_public_servers_servers_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Server */
        post: operations["join_server_servers_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{server_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Server */
        get: operations["get_server_servers__server_id__get"];
        put?: never;
        post?: never;
        /** Delete Server */
        delete: operations["delete_server_servers__server_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{server_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_servers__server_id__leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{server_id}/cohort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cohort */
        get: operations["get_cohort_servers__server_id__cohort_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{world_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get World */
        get: operations["get_world_worlds__world_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{world_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Attempt */
        post: operations["create_attempt_worlds__world_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{world_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_worlds__world_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{world_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Concept */
        post: operations["explain_concept_worlds__world_id__explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttemptIn
         * @example {
         *       "archetype": "quest",
         *       "option_id": "op_same",
         *       "scene_id": "sc_pred_overfit"
         *     }
         */
        AttemptIn: {
            /**
             * Archetype
             * @enum {string}
             */
            archetype: "quest" | "gauntlet";
            /** Scene Id */
            scene_id: string;
            /** Option Id */
            option_id: string;
        };
        /**
         * AttemptOut
         * @example {
         *       "attempt_id": "7d4e6f9a0b1c2d3e4f5a6b3f2a9c1e8b",
         *       "correct": false,
         *       "first_time": true,
         *       "misconception": {
         *         "correction": "The two scores decouple once the model starts fitting noise. A near-perfect training score with no validation check is the classic warning sign, not a result.",
         *         "id": "high_train_high_test",
         *         "statement": "99 percent on training means roughly 99 percent on new data."
         *       },
         *       "reveal": "Far worse, and the training score gave no warning. It kept climbing while performance on unseen data fell, because the model was fitting the noise in its own study book. That widening gap is the signature of overfitting.",
         *       "server_xp": 14,
         *       "world_xp": 14,
         *       "xp_awarded": 2
         *     }
         */
        AttemptOut: {
            /** Attempt Id */
            attempt_id: string;
            /** Correct */
            correct: boolean;
            /** Xp Awarded */
            xp_awarded: number;
            /** First Time */
            first_time: boolean;
            misconception?: components["schemas"]["MisconceptionOut"] | null;
            /** Reveal */
            reveal: string;
            /** World Xp */
            world_xp: number;
            /** Server Xp */
            server_xp: number;
        };
        /** Body_create_server_servers_post */
        Body_create_server_servers_post: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
            /** Pet */
            pet: string;
            /** Text */
            text?: string | null;
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /** Chapter */
        Chapter: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Concept Ids */
            concept_ids: string[];
            /**
             * Background
             * @enum {string}
             */
            background: "cavern" | "forest_path" | "ruins" | "observatory" | "shore" | "village";
            /** Scenes */
            scenes: (components["schemas"]["DialogueScene"] | components["schemas"]["PredictionScene"] | components["schemas"]["SimulationScene"])[];
        };
        /**
         * CohortOut
         * @example {
         *       "distribution": [
         *         {
         *           "concept_id": "overfitting",
         *           "options": [
         *             {
         *               "correct": false,
         *               "count": 14,
         *               "misconception_id": "high_train_high_test",
         *               "option_id": "op_same",
         *               "pct": 52,
         *               "text": "It scores about 99 percent again"
         *             },
         *             {
         *               "correct": true,
         *               "count": 11,
         *               "option_id": "op_worse",
         *               "pct": 41,
         *               "text": "It scores far worse"
         *             },
         *             {
         *               "correct": false,
         *               "count": 2,
         *               "misconception_id": "overfitting_is_bad_data",
         *               "option_id": "op_refuse",
         *               "pct": 7,
         *               "text": "It refuses to answer"
         *             }
         *           ],
         *           "scene_id": "sc_pred_overfit",
         *           "world_id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a"
         *         }
         *       ],
         *       "entries": [
         *         {
         *           "attempts": 11,
         *           "display_name": "Grace",
         *           "rank": 1,
         *           "user_id": "0b1c2d3e4f5a6b3f2a9c1e8b7d4e6f9a",
         *           "xp": 95
         *         },
         *         {
         *           "attempts": 8,
         *           "display_name": "Linus",
         *           "rank": 2,
         *           "user_id": "1c2d3e4f5a6b3f2a9c1e8b7d4e6f9a0b",
         *           "xp": 60
         *         },
         *         {
         *           "attempts": 6,
         *           "display_name": "Ada L.",
         *           "rank": 3,
         *           "user_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *           "xp": 42
         *         }
         *       ],
         *       "hardest_concept": {
         *         "concept_id": "overfitting",
         *         "label": "Overfitting",
         *         "wrong_pct": 59
         *       },
         *       "me": {
         *         "attempts": 6,
         *         "display_name": "Ada L.",
         *         "rank": 3,
         *         "user_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *         "xp": 42
         *       },
         *       "members_count": 27,
         *       "predictions_made": 143,
         *       "server_id": "9c1e8b7d4e6f9a0b1c2d3e4f5a6b3f2a"
         *     }
         */
        CohortOut: {
            /** Server Id */
            server_id: string;
            me?: components["schemas"]["LeaderboardEntry"] | null;
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
            /** Members Count */
            members_count: number;
            /** Predictions Made */
            predictions_made: number;
            /** Distribution */
            distribution: components["schemas"]["DistributionEntry"][];
            hardest_concept?: components["schemas"]["HardestConcept"] | null;
        };
        /** Concept */
        Concept: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Summary */
            summary: string;
            /**
             * Bloom Level
             * @enum {string}
             */
            bloom_level: "remember" | "understand" | "apply" | "analyse" | "evaluate" | "create";
            /** Prerequisites */
            prerequisites: string[];
            /** Source Spans */
            source_spans: components["schemas"]["SourceSpan"][];
            /** Misconceptions */
            misconceptions: components["schemas"]["Misconception"][];
        };
        /**
         * ConceptOut
         * @example {
         *       "id": "overfitting",
         *       "label": "Overfitting",
         *       "summary": "A model overfits when it captures noise specific to the training set. Training error keeps falling while error on new data rises."
         *     }
         */
        ConceptOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Summary */
            summary: string;
        };
        /** CourseGraph */
        CourseGraph: {
            /**
             * Schema Version
             * @constant
             * @enum {string}
             */
            schema_version: "1.0";
            /** Graph Id */
            graph_id: string;
            source: components["schemas"]["GraphSource"];
            /** Concepts */
            concepts: components["schemas"]["Concept"][];
        };
        /** DialogueScene */
        DialogueScene: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dialogue";
            /** Id */
            id: string;
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "explorer" | "mentor_owl" | "rival" | "villager";
            /** Props */
            props?: ("doorway_pair" | "chart_frame" | "lantern" | "crystal_cluster" | "chest" | "signpost")[] | null;
            /** Lines */
            lines: string[];
        };
        /**
         * DistributionEntry
         * @example {
         *       "concept_id": "overfitting",
         *       "options": [
         *         {
         *           "correct": false,
         *           "count": 14,
         *           "misconception_id": "high_train_high_test",
         *           "option_id": "op_same",
         *           "pct": 52,
         *           "text": "It scores about 99 percent again"
         *         },
         *         {
         *           "correct": true,
         *           "count": 11,
         *           "option_id": "op_worse",
         *           "pct": 41,
         *           "text": "It scores far worse"
         *         },
         *         {
         *           "correct": false,
         *           "count": 2,
         *           "misconception_id": "overfitting_is_bad_data",
         *           "option_id": "op_refuse",
         *           "pct": 7,
         *           "text": "It refuses to answer"
         *         }
         *       ],
         *       "scene_id": "sc_pred_overfit",
         *       "world_id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a"
         *     }
         */
        DistributionEntry: {
            /** World Id */
            world_id: string;
            /** Scene Id */
            scene_id: string;
            /** Concept Id */
            concept_id: string;
            /** Options */
            options: components["schemas"]["DistributionOption"][];
        };
        /**
         * DistributionOption
         * @example {
         *       "correct": false,
         *       "count": 14,
         *       "misconception_id": "high_train_high_test",
         *       "option_id": "op_same",
         *       "pct": 52,
         *       "text": "It scores about 99 percent again"
         *     }
         */
        DistributionOption: {
            /** Option Id */
            option_id: string;
            /** Text */
            text: string;
            /** Correct */
            correct: boolean;
            /** Misconception Id */
            misconception_id?: string | null;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /**
         * ExplainIn
         * @example {
         *       "concept_id": "overfitting",
         *       "text": "Overfitting is when the model learns the noise in the training set, so training error keeps dropping but error on new data goes up."
         *     }
         */
        ExplainIn: {
            /** Concept Id */
            concept_id: string;
            /** Text */
            text: string;
        };
        /**
         * ExplainOut
         * @example {
         *       "concept": {
         *         "id": "overfitting",
         *         "label": "Overfitting",
         *         "summary": "A model overfits when it captures noise specific to the training set. Training error keeps falling while error on new data rises."
         *       },
         *       "feedback": "You named the mechanism (fitting noise) and the signature (train/validation gap). Mention that capacity, not data quality, is the cause.",
         *       "score": 82,
         *       "server_xp": 62,
         *       "verdict": "pass",
         *       "world_xp": 62,
         *       "xp_awarded": 25
         *     }
         */
        ExplainOut: {
            /** Score */
            score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "pass" | "partial" | "fail";
            /** Xp Awarded */
            xp_awarded: number;
            /** Feedback */
            feedback: string;
            /** Misconception Id */
            misconception_id?: string | null;
            concept: components["schemas"]["ConceptOut"];
            /** World Xp */
            world_xp: number;
            /** Server Xp */
            server_xp: number;
        };
        /**
         * ExplanationProgress
         * @example {
         *       "concept_id": "training_data",
         *       "created_at": "2026-08-22T10:02:11Z",
         *       "score": 78,
         *       "verdict": "pass"
         *     }
         */
        ExplanationProgress: {
            /** Concept Id */
            concept_id: string;
            /** Score */
            score: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "pass" | "partial" | "fail";
            /** Created At */
            created_at: string;
        };
        /** Game */
        Game: {
            /**
             * Schema Version
             * @constant
             * @enum {string}
             */
            schema_version: "1.0";
            /** Game Id */
            game_id: string;
            /** Graph Id */
            graph_id: string;
            /**
             * Archetype
             * @enum {string}
             */
            archetype: "quest" | "gauntlet";
            /** Title */
            title: string;
            /** Chapters */
            chapters: components["schemas"]["Chapter"][];
        };
        /** GamesOut */
        GamesOut: {
            quest?: components["schemas"]["Game"] | null;
            gauntlet?: components["schemas"]["Game"] | null;
        };
        /**
         * GenerationEventOut
         * @example {
         *       "at": "2026-08-22T09:20:41Z",
         *       "level": "info",
         *       "message": "Extracted 5 concepts",
         *       "stage": "graph",
         *       "world_id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a"
         *     }
         */
        GenerationEventOut: {
            /** Stage */
            stage: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warn" | "error";
            /** Message */
            message: string;
            /** World Id */
            world_id?: string | null;
            /** At */
            at: string;
        };
        /** GraphSource */
        GraphSource: {
            /** Title */
            title: string;
            /** Segment Count */
            segment_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HardestConcept
         * @example {
         *       "concept_id": "overfitting",
         *       "label": "Overfitting",
         *       "wrong_pct": 59
         *     }
         */
        HardestConcept: {
            /** Concept Id */
            concept_id: string;
            /** Label */
            label: string;
            /** Wrong Pct */
            wrong_pct: number;
        };
        /**
         * HealthOut
         * @example {
         *       "db": "ok",
         *       "llm": "live",
         *       "status": "ok",
         *       "version": "0.1.0"
         *     }
         */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error";
            /**
             * Llm
             * @enum {string}
             */
            llm: "live" | "fixtures";
            /** Version */
            version: string;
        };
        /**
         * JoinIn
         * @example {
         *       "join_code": "demo01"
         *     }
         */
        JoinIn: {
            /** Join Code */
            join_code: string;
        };
        /**
         * JoinOut
         * @example {
         *       "already_member": false,
         *       "server": {
         *         "created_at": "2026-08-22T09:20:00Z",
         *         "id": "9c1e8b7d4e6f9a0b1c2d3e4f5a6b3f2a",
         *         "is_public": true,
         *         "join_code": "K7Q2MX",
         *         "member_count": 1,
         *         "my_role": "owner",
         *         "my_xp": 0,
         *         "name": "Intro to ML — Week 3",
         *         "owner_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *         "pet": "owl",
         *         "status": "processing",
         *         "world_count": 0
         *       }
         *     }
         */
        JoinOut: {
            server: components["schemas"]["ServerSummary"];
            /** Already Member */
            already_member: boolean;
        };
        /**
         * LeaderboardEntry
         * @example {
         *       "attempts": 6,
         *       "display_name": "Ada L.",
         *       "rank": 3,
         *       "user_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *       "xp": 42
         *     }
         */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Xp */
            xp: number;
            /** Attempts */
            attempts: number;
        };
        /**
         * LeaderboardOut
         * @example {
         *       "entries": [
         *         {
         *           "attempts": 11,
         *           "display_name": "Grace",
         *           "rank": 1,
         *           "user_id": "0b1c2d3e4f5a6b3f2a9c1e8b7d4e6f9a",
         *           "xp": 95
         *         },
         *         {
         *           "attempts": 8,
         *           "display_name": "Linus",
         *           "rank": 2,
         *           "user_id": "1c2d3e4f5a6b3f2a9c1e8b7d4e6f9a0b",
         *           "xp": 60
         *         },
         *         {
         *           "attempts": 6,
         *           "display_name": "Ada L.",
         *           "rank": 3,
         *           "user_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *           "xp": 42
         *         }
         *       ],
         *       "me": {
         *         "attempts": 6,
         *         "display_name": "Ada L.",
         *         "rank": 3,
         *         "user_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *         "xp": 42
         *       },
         *       "server_id": "9c1e8b7d4e6f9a0b1c2d3e4f5a6b3f2a"
         *     }
         */
        LeaderboardOut: {
            /** Server Id */
            server_id: string;
            me?: components["schemas"]["LeaderboardEntry"] | null;
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /**
         * LoginIn
         * @example {
         *       "email": "ada@example.com",
         *       "password": "correct-horse-battery"
         *     }
         */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Misconception */
        Misconception: {
            /** Id */
            id: string;
            /** Statement */
            statement: string;
            /** Why Plausible */
            why_plausible: string;
            /** Correction */
            correction: string;
        };
        /**
         * MisconceptionOut
         * @example {
         *       "correction": "The two scores decouple once the model starts fitting noise. A near-perfect training score with no validation check is the classic warning sign, not a result.",
         *       "id": "high_train_high_test",
         *       "statement": "99 percent on training means roughly 99 percent on new data."
         *     }
         */
        MisconceptionOut: {
            /** Id */
            id: string;
            /** Statement */
            statement: string;
            /** Correction */
            correction: string;
        };
        /**
         * MyProgress
         * @example {
         *       "explained_concept_ids": [
         *         "training_data"
         *       ],
         *       "scenes_attempted": 2,
         *       "scenes_correct": 1,
         *       "scenes_total": 8,
         *       "xp": 12
         *     }
         */
        MyProgress: {
            /** Xp */
            xp: number;
            /** Scenes Total */
            scenes_total: number;
            /** Scenes Attempted */
            scenes_attempted: number;
            /** Scenes Correct */
            scenes_correct: number;
            /** Explained Concept Ids */
            explained_concept_ids: string[];
        };
        /** Option */
        Option: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Correct */
            correct: boolean;
            /** Misconception Id */
            misconception_id?: string | null;
        };
        /** PredictionScene */
        PredictionScene: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "prediction";
            /** Id */
            id: string;
            /** Concept Id */
            concept_id: string;
            /** Props */
            props?: ("doorway_pair" | "chart_frame" | "lantern" | "crystal_cluster" | "chest" | "signpost")[] | null;
            /** Prompt */
            prompt: string;
            /** Options */
            options: components["schemas"]["Option"][];
            /** Reveal */
            reveal: string;
        };
        /**
         * ProfileUpdateIn
         * @description All fields optional; only keys present in the body are changed.
         * @example {
         *       "about": "Second-year CS student.",
         *       "display_name": "Ada L.",
         *       "industry": "Software",
         *       "role": "student"
         *     }
         */
        ProfileUpdateIn: {
            /** Display Name */
            display_name?: string | null;
            /** Role */
            role?: ("student" | "teacher") | null;
            /** Industry */
            industry?: string | null;
            /** About */
            about?: string | null;
        };
        /**
         * ProgressOut
         * @example {
         *       "explanations": [
         *         {
         *           "concept_id": "training_data",
         *           "created_at": "2026-08-22T10:02:11Z",
         *           "score": 78,
         *           "verdict": "pass"
         *         }
         *       ],
         *       "scenes": [
         *         {
         *           "archetype": "quest",
         *           "attempts": 2,
         *           "best_correct": true,
         *           "chosen_option_id": "op_same",
         *           "scene_id": "sc_pred_overfit"
         *         }
         *       ],
         *       "world_id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a",
         *       "xp": 37
         *     }
         */
        ProgressOut: {
            /** World Id */
            world_id: string;
            /** Xp */
            xp: number;
            /** Scenes */
            scenes: components["schemas"]["SceneProgress"][];
            /** Explanations */
            explanations: components["schemas"]["ExplanationProgress"][];
        };
        /**
         * RegisterIn
         * @example {
         *       "display_name": "Ada Lovelace",
         *       "email": "ada@example.com",
         *       "password": "correct-horse-battery"
         *     }
         */
        RegisterIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /**
         * SceneProgress
         * @example {
         *       "archetype": "quest",
         *       "attempts": 2,
         *       "best_correct": true,
         *       "chosen_option_id": "op_same",
         *       "scene_id": "sc_pred_overfit"
         *     }
         */
        SceneProgress: {
            /** Scene Id */
            scene_id: string;
            /**
             * Archetype
             * @enum {string}
             */
            archetype: "quest" | "gauntlet";
            /** Attempts */
            attempts: number;
            /** Best Correct */
            best_correct: boolean;
            /** Chosen Option Id */
            chosen_option_id?: string | null;
        };
        /**
         * ServerDetail
         * @example {
         *       "created_at": "2026-08-22T09:20:00Z",
         *       "id": "9c1e8b7d4e6f9a0b1c2d3e4f5a6b3f2a",
         *       "is_public": true,
         *       "join_code": "K7Q2MX",
         *       "member_count": 1,
         *       "my_role": "owner",
         *       "my_xp": 0,
         *       "name": "Intro to ML — Week 3",
         *       "owner_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *       "pet": "owl",
         *       "progress": {
         *         "log": [
         *           {
         *             "at": "2026-08-22T09:20:41Z",
         *             "level": "info",
         *             "message": "Extracted 5 concepts",
         *             "stage": "graph",
         *             "world_id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a"
         *           }
         *         ],
         *         "percent": 62,
         *         "stage": "quest",
         *         "worlds_failed": 0,
         *         "worlds_ready": 1,
         *         "worlds_total": 2
         *       },
         *       "status": "processing",
         *       "world_count": 2,
         *       "worlds": [
         *         {
         *           "blurb": "Training data, generalisation and overfitting.",
         *           "concept_count": 5,
         *           "gauntlet_id": "g3xn8vr1",
         *           "graph_id": "wk3ml0a1",
         *           "id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a",
         *           "idx": 0,
         *           "my_completion": 0,
         *           "my_xp": 0,
         *           "quest_id": "q7kp2wm4",
         *           "scene_count": 8,
         *           "stage": "done",
         *           "status": "ready",
         *           "title": "The Archivist's Cavern"
         *         }
         *       ]
         *     }
         */
        ServerDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Join Code */
            join_code?: string | null;
            /** Is Public */
            is_public: boolean;
            /** Pet */
            pet: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Error */
            error?: string | null;
            /** Owner Id */
            owner_id: string;
            /** Member Count */
            member_count: number;
            /** World Count */
            world_count: number;
            /** My Role */
            my_role?: ("owner" | "member") | null;
            /** My Xp */
            my_xp: number;
            /** Created At */
            created_at: string;
            progress: components["schemas"]["ServerProgressOut"];
            /** Worlds */
            worlds: components["schemas"]["WorldSummary"][];
        };
        /**
         * ServerProgressOut
         * @example {
         *       "log": [
         *         {
         *           "at": "2026-08-22T09:20:41Z",
         *           "level": "info",
         *           "message": "Extracted 5 concepts",
         *           "stage": "graph",
         *           "world_id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a"
         *         }
         *       ],
         *       "percent": 62,
         *       "stage": "quest",
         *       "worlds_failed": 0,
         *       "worlds_ready": 1,
         *       "worlds_total": 2
         *     }
         */
        ServerProgressOut: {
            /** Worlds Total */
            worlds_total: number;
            /** Worlds Ready */
            worlds_ready: number;
            /** Worlds Failed */
            worlds_failed: number;
            /** Stage */
            stage?: string | null;
            /** Percent */
            percent: number;
            /** Log */
            log: components["schemas"]["GenerationEventOut"][];
        };
        /**
         * ServerSummary
         * @example {
         *       "created_at": "2026-08-22T09:20:00Z",
         *       "id": "9c1e8b7d4e6f9a0b1c2d3e4f5a6b3f2a",
         *       "is_public": true,
         *       "join_code": "K7Q2MX",
         *       "member_count": 1,
         *       "my_role": "owner",
         *       "my_xp": 0,
         *       "name": "Intro to ML — Week 3",
         *       "owner_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *       "pet": "owl",
         *       "status": "processing",
         *       "world_count": 0
         *     }
         */
        ServerSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Join Code */
            join_code?: string | null;
            /** Is Public */
            is_public: boolean;
            /** Pet */
            pet: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Error */
            error?: string | null;
            /** Owner Id */
            owner_id: string;
            /** Member Count */
            member_count: number;
            /** World Count */
            world_count: number;
            /** My Role */
            my_role?: ("owner" | "member") | null;
            /** My Xp */
            my_xp: number;
            /** Created At */
            created_at: string;
        };
        /**
         * ServersOut
         * @example {
         *       "servers": [
         *         {
         *           "created_at": "2026-08-22T09:20:00Z",
         *           "id": "9c1e8b7d4e6f9a0b1c2d3e4f5a6b3f2a",
         *           "is_public": true,
         *           "join_code": "K7Q2MX",
         *           "member_count": 1,
         *           "my_role": "owner",
         *           "my_xp": 0,
         *           "name": "Intro to ML — Week 3",
         *           "owner_id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *           "pet": "owl",
         *           "status": "processing",
         *           "world_count": 0
         *         }
         *       ]
         *     }
         */
        ServersOut: {
            /** Servers */
            servers: components["schemas"]["ServerSummary"][];
        };
        /** SimulationScene */
        SimulationScene: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "simulation";
            /** Id */
            id: string;
            /** Concept Id */
            concept_id: string;
            /**
             * Widget
             * @enum {string}
             */
            widget: "curve_fit" | "threshold_slider" | "sorting_bins" | "graph_walk";
            /** Instruction */
            instruction: string;
            /** Success Condition */
            success_condition?: string | null;
        };
        /** SourceSpan */
        SourceSpan: {
            /** Segment Id */
            segment_id: number;
            /** Quote */
            quote: string;
        };
        /**
         * TokenOut
         * @example {
         *       "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZjJhIn0.sig",
         *       "token_type": "bearer",
         *       "user": {
         *         "about": "Teaching analytical engines since 1843.",
         *         "created_at": "2026-08-22T09:15:00Z",
         *         "display_name": "Ada Lovelace",
         *         "email": "ada@example.com",
         *         "id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *         "industry": "Mathematics",
         *         "role": "teacher"
         *       }
         *     }
         */
        TokenOut: {
            /** Token */
            token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             * @enum {string}
             */
            token_type: "bearer";
            user: components["schemas"]["UserOut"];
        };
        /**
         * UserOut
         * @example {
         *       "about": "Teaching analytical engines since 1843.",
         *       "created_at": "2026-08-22T09:15:00Z",
         *       "display_name": "Ada Lovelace",
         *       "email": "ada@example.com",
         *       "id": "3f2a9c1e8b7d4e6f9a0b1c2d3e4f5a6b",
         *       "industry": "Mathematics",
         *       "role": "teacher"
         *     }
         */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role?: ("student" | "teacher") | null;
            /** Industry */
            industry?: string | null;
            /** About */
            about?: string | null;
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorldDetail
         * @example {
         *       "blurb": "Training data, generalisation and overfitting.",
         *       "concept_count": 5,
         *       "games": {},
         *       "gauntlet_id": "g3xn8vr1",
         *       "graph_id": "wk3ml0a1",
         *       "id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a",
         *       "idx": 0,
         *       "my_completion": 0.25,
         *       "my_progress": {
         *         "explained_concept_ids": [
         *           "training_data"
         *         ],
         *         "scenes_attempted": 2,
         *         "scenes_correct": 1,
         *         "scenes_total": 8,
         *         "xp": 12
         *       },
         *       "my_xp": 12,
         *       "quest_id": "q7kp2wm4",
         *       "scene_count": 8,
         *       "segment_end": 14,
         *       "segment_start": 0,
         *       "server_id": "9c1e8b7d4e6f9a0b1c2d3e4f5a6b3f2a",
         *       "stage": "done",
         *       "status": "ready",
         *       "title": "The Archivist's Cavern"
         *     }
         */
        WorldDetail: {
            /** Id */
            id: string;
            /** Idx */
            idx: number;
            /** Title */
            title: string;
            /** Blurb */
            blurb?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Stage */
            stage?: string | null;
            /** Error */
            error?: string | null;
            /** Graph Id */
            graph_id?: string | null;
            /** Quest Id */
            quest_id?: string | null;
            /** Gauntlet Id */
            gauntlet_id?: string | null;
            /** Concept Count */
            concept_count: number;
            /** Scene Count */
            scene_count: number;
            /** My Xp */
            my_xp: number;
            /** My Completion */
            my_completion: number;
            /** Server Id */
            server_id: string;
            /** Segment Start */
            segment_start: number;
            /** Segment End */
            segment_end: number;
            graph?: components["schemas"]["CourseGraph"] | null;
            games: components["schemas"]["GamesOut"];
            my_progress: components["schemas"]["MyProgress"];
        };
        /**
         * WorldSummary
         * @example {
         *       "blurb": "Training data, generalisation and overfitting.",
         *       "concept_count": 5,
         *       "gauntlet_id": "g3xn8vr1",
         *       "graph_id": "wk3ml0a1",
         *       "id": "5b3f2a9c1e8b7d4e6f9a0b1c2d3e4f6a",
         *       "idx": 0,
         *       "my_completion": 0,
         *       "my_xp": 0,
         *       "quest_id": "q7kp2wm4",
         *       "scene_count": 8,
         *       "stage": "done",
         *       "status": "ready",
         *       "title": "The Archivist's Cavern"
         *     }
         */
        WorldSummary: {
            /** Id */
            id: string;
            /** Idx */
            idx: number;
            /** Title */
            title: string;
            /** Blurb */
            blurb?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Stage */
            stage?: string | null;
            /** Error */
            error?: string | null;
            /** Graph Id */
            graph_id?: string | null;
            /** Quest Id */
            quest_id?: string | null;
            /** Gauntlet Id */
            gauntlet_id?: string | null;
            /** Concept Count */
            concept_count: number;
            /** Scene Count */
            scene_count: number;
            /** My Xp */
            my_xp: number;
            /** My Completion */
            my_completion: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_servers_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServersOut"];
                };
            };
        };
    };
    create_server_servers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_server_servers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_servers_servers_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServersOut"];
                };
            };
        };
    };
    join_server_servers_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_servers__server_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_server_servers__server_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_servers__server_id__leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cohort_servers__server_id__cohort_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CohortOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_world_worlds__world_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attempt_worlds__world_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_worlds__world_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_concept_worlds__world_id__explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
